apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: service-viewer
  namespace: istio-samples
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
    constraints:
    - key: "destination.labels[app]"
      values: ["customer"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-service-viewer
  namespace: istio-samples
spec:
  subjects:
  - user: "*"
    properties:
      request.auth.claims[preferred_username]: "demo"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: other-service-viewer
  namespace: istio-samples
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
    constraints:
    - key: "destination.labels[app]"
      values: ["preference", "recommendation"]
---    
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-other-service-viewer
  namespace: istio-samples
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "other-service-viewer"